# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 807)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setObjectName("tabWidget")
        self.pNetflix_tab = QtWidgets.QWidget()
        self.pNetflix_tab.setAutoFillBackground(False)
        self.pNetflix_tab.setObjectName("pNetflix_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pNetflix_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.pNetflix_tab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.dataRatingsGroupBox = QtWidgets.QGroupBox(self.groupBox_8)
        self.dataRatingsGroupBox.setObjectName("dataRatingsGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dataRatingsGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.decompressGroupBox = QtWidgets.QGroupBox(self.dataRatingsGroupBox)
        self.decompressGroupBox.setObjectName("decompressGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.decompressGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.decompressButton = QtWidgets.QPushButton(self.decompressGroupBox)
        self.decompressButton.setObjectName("decompressButton")
        self.horizontalLayout.addWidget(self.decompressButton)
        self.decompressProgressBar = QtWidgets.QProgressBar(self.decompressGroupBox)
        self.decompressProgressBar.setProperty("value", 0)
        self.decompressProgressBar.setObjectName("decompressProgressBar")
        self.horizontalLayout.addWidget(self.decompressProgressBar)
        self.verticalLayout.addWidget(self.decompressGroupBox)
        self.groupBox = QtWidgets.QGroupBox(self.dataRatingsGroupBox)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LoadButton = QtWidgets.QPushButton(self.groupBox)
        self.LoadButton.setEnabled(False)
        self.LoadButton.setObjectName("LoadButton")
        self.horizontalLayout_2.addWidget(self.LoadButton)
        self.loadProgressBar = QtWidgets.QProgressBar(self.groupBox)
        self.loadProgressBar.setProperty("value", 0)
        self.loadProgressBar.setObjectName("loadProgressBar")
        self.horizontalLayout_2.addWidget(self.loadProgressBar)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_11.addWidget(self.dataRatingsGroupBox)
        self.subsetRatingsDataBox = QtWidgets.QGroupBox(self.groupBox_8)
        self.subsetRatingsDataBox.setObjectName("subsetRatingsDataBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.subsetRatingsDataBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.reduceMoviesGroup = QtWidgets.QGroupBox(self.subsetRatingsDataBox)
        self.reduceMoviesGroup.setObjectName("reduceMoviesGroup")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.reduceMoviesGroup)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.reduceMoviesButton = QtWidgets.QPushButton(self.reduceMoviesGroup)
        self.reduceMoviesButton.setEnabled(False)
        self.reduceMoviesButton.setObjectName("reduceMoviesButton")
        self.horizontalLayout_4.addWidget(self.reduceMoviesButton)
        self.reduceMoviesProgressBar = QtWidgets.QProgressBar(self.reduceMoviesGroup)
        self.reduceMoviesProgressBar.setProperty("value", 0)
        self.reduceMoviesProgressBar.setObjectName("reduceMoviesProgressBar")
        self.horizontalLayout_4.addWidget(self.reduceMoviesProgressBar)
        self.verticalLayout_2.addWidget(self.reduceMoviesGroup)
        self.groupBox_2 = QtWidgets.QGroupBox(self.subsetRatingsDataBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.reduceUsersButton = QtWidgets.QPushButton(self.groupBox_2)
        self.reduceUsersButton.setEnabled(False)
        self.reduceUsersButton.setObjectName("reduceUsersButton")
        self.horizontalLayout_5.addWidget(self.reduceUsersButton)
        self.reduceUsersProgressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.reduceUsersProgressBar.setProperty("value", 0)
        self.reduceUsersProgressBar.setObjectName("reduceUsersProgressBar")
        self.horizontalLayout_5.addWidget(self.reduceUsersProgressBar)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.SRSWRGroupBox = QtWidgets.QGroupBox(self.subsetRatingsDataBox)
        self.SRSWRGroupBox.setObjectName("SRSWRGroupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.SRSWRGroupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget = QtWidgets.QWidget(self.SRSWRGroupBox)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.reduceSRSWRButton = QtWidgets.QPushButton(self.widget)
        self.reduceSRSWRButton.setEnabled(False)
        self.reduceSRSWRButton.setObjectName("reduceSRSWRButton")
        self.verticalLayout_4.addWidget(self.reduceSRSWRButton)
        self.horizontalLayout_6.addWidget(self.widget)
        self.randomSeedGroupBox = QtWidgets.QGroupBox(self.SRSWRGroupBox)
        self.randomSeedGroupBox.setObjectName("randomSeedGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.randomSeedGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.randomSeedSpinBox = QtWidgets.QSpinBox(self.randomSeedGroupBox)
        self.randomSeedSpinBox.setProperty("value", 42)
        self.randomSeedSpinBox.setObjectName("randomSeedSpinBox")
        self.verticalLayout_3.addWidget(self.randomSeedSpinBox)
        self.horizontalLayout_6.addWidget(self.randomSeedGroupBox)
        self.reduceSRSWRProgressBar = QtWidgets.QProgressBar(self.SRSWRGroupBox)
        self.reduceSRSWRProgressBar.setProperty("value", 0)
        self.reduceSRSWRProgressBar.setObjectName("reduceSRSWRProgressBar")
        self.horizontalLayout_6.addWidget(self.reduceSRSWRProgressBar)
        self.verticalLayout_2.addWidget(self.SRSWRGroupBox)
        self.verticalLayout_11.addWidget(self.subsetRatingsDataBox)
        self.saveGroupBox = QtWidgets.QGroupBox(self.groupBox_8)
        self.saveGroupBox.setObjectName("saveGroupBox")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.saveGroupBox)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.nd_saveButton = QtWidgets.QPushButton(self.saveGroupBox)
        self.nd_saveButton.setEnabled(False)
        self.nd_saveButton.setObjectName("nd_saveButton")
        self.horizontalLayout_16.addWidget(self.nd_saveButton)
        self.nd_saveProgressBar = QtWidgets.QProgressBar(self.saveGroupBox)
        self.nd_saveProgressBar.setProperty("value", 0)
        self.nd_saveProgressBar.setObjectName("nd_saveProgressBar")
        self.horizontalLayout_16.addWidget(self.nd_saveProgressBar)
        self.verticalLayout_11.addWidget(self.saveGroupBox)
        self.gridLayout_2.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.pNetflix_tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.nd_loadpreprocessed_Button = QtWidgets.QPushButton(self.groupBox_7)
        self.nd_loadpreprocessed_Button.setObjectName("nd_loadpreprocessed_Button")
        self.horizontalLayout_18.addWidget(self.nd_loadpreprocessed_Button)
        self.nd_loadpreprocessed_ProgressBar = QtWidgets.QProgressBar(self.groupBox_7)
        self.nd_loadpreprocessed_ProgressBar.setProperty("value", 0)
        self.nd_loadpreprocessed_ProgressBar.setObjectName("nd_loadpreprocessed_ProgressBar")
        self.horizontalLayout_18.addWidget(self.nd_loadpreprocessed_ProgressBar)
        self.gridLayout_2.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pNetflix_tab, "")
        self.pMetaData_tab = QtWidgets.QWidget()
        self.pMetaData_tab.setEnabled(True)
        self.pMetaData_tab.setObjectName("pMetaData_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pMetaData_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.pMetaData_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_8 = QtWidgets.QWidget(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.c_loadPIMDB_Button = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_loadPIMDB_Button.sizePolicy().hasHeightForWidth())
        self.c_loadPIMDB_Button.setSizePolicy(sizePolicy)
        self.c_loadPIMDB_Button.setObjectName("c_loadPIMDB_Button")
        self.horizontalLayout_7.addWidget(self.c_loadPIMDB_Button)
        self.c_loadPIMDB_ProgressBar = QtWidgets.QProgressBar(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_loadPIMDB_ProgressBar.sizePolicy().hasHeightForWidth())
        self.c_loadPIMDB_ProgressBar.setSizePolicy(sizePolicy)
        self.c_loadPIMDB_ProgressBar.setProperty("value", 0)
        self.c_loadPIMDB_ProgressBar.setObjectName("c_loadPIMDB_ProgressBar")
        self.horizontalLayout_7.addWidget(self.c_loadPIMDB_ProgressBar)
        self.verticalLayout_13.addWidget(self.widget_8)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        self.groupBox_6 = QtWidgets.QGroupBox(self.pMetaData_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.md_loadNetflix_Box = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.md_loadNetflix_Box.sizePolicy().hasHeightForWidth())
        self.md_loadNetflix_Box.setSizePolicy(sizePolicy)
        self.md_loadNetflix_Box.setObjectName("md_loadNetflix_Box")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.md_loadNetflix_Box)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.md_loadNetflix_button = QtWidgets.QPushButton(self.md_loadNetflix_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.md_loadNetflix_button.sizePolicy().hasHeightForWidth())
        self.md_loadNetflix_button.setSizePolicy(sizePolicy)
        self.md_loadNetflix_button.setObjectName("md_loadNetflix_button")
        self.horizontalLayout_8.addWidget(self.md_loadNetflix_button)
        self.md_loadNetflix_progressBar = QtWidgets.QProgressBar(self.md_loadNetflix_Box)
        self.md_loadNetflix_progressBar.setProperty("value", 0)
        self.md_loadNetflix_progressBar.setObjectName("md_loadNetflix_progressBar")
        self.horizontalLayout_8.addWidget(self.md_loadNetflix_progressBar)
        self.verticalLayout_12.addWidget(self.md_loadNetflix_Box)
        self.md_joinBox = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.md_joinBox.sizePolicy().hasHeightForWidth())
        self.md_joinBox.setSizePolicy(sizePolicy)
        self.md_joinBox.setObjectName("md_joinBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.md_joinBox)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.md_joinIMDB_progressBar = QtWidgets.QPushButton(self.md_joinBox)
        self.md_joinIMDB_progressBar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.md_joinIMDB_progressBar.sizePolicy().hasHeightForWidth())
        self.md_joinIMDB_progressBar.setSizePolicy(sizePolicy)
        self.md_joinIMDB_progressBar.setObjectName("md_joinIMDB_progressBar")
        self.horizontalLayout_9.addWidget(self.md_joinIMDB_progressBar)
        self.md_joinIMDB_Button = QtWidgets.QProgressBar(self.md_joinBox)
        self.md_joinIMDB_Button.setProperty("value", 0)
        self.md_joinIMDB_Button.setObjectName("md_joinIMDB_Button")
        self.horizontalLayout_9.addWidget(self.md_joinIMDB_Button)
        self.verticalLayout_12.addWidget(self.md_joinBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.md_addIMDB_joinButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.md_addIMDB_joinButton.sizePolicy().hasHeightForWidth())
        self.md_addIMDB_joinButton.setSizePolicy(sizePolicy)
        self.md_addIMDB_joinButton.setObjectName("md_addIMDB_joinButton")
        self.horizontalLayout_14.addWidget(self.md_addIMDB_joinButton)
        self.md_addIMDB_joinProgressBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.md_addIMDB_joinProgressBar.setProperty("value", 0)
        self.md_addIMDB_joinProgressBar.setObjectName("md_addIMDB_joinProgressBar")
        self.horizontalLayout_14.addWidget(self.md_addIMDB_joinProgressBar)
        self.verticalLayout_12.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.md_saveButton = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.md_saveButton.sizePolicy().hasHeightForWidth())
        self.md_saveButton.setSizePolicy(sizePolicy)
        self.md_saveButton.setObjectName("md_saveButton")
        self.horizontalLayout_15.addWidget(self.md_saveButton)
        self.md_saveProgressBar = QtWidgets.QProgressBar(self.groupBox_4)
        self.md_saveProgressBar.setProperty("value", 0)
        self.md_saveProgressBar.setObjectName("md_saveProgressBar")
        self.horizontalLayout_15.addWidget(self.md_saveProgressBar)
        self.verticalLayout_12.addWidget(self.groupBox_4)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.pMetaData_tab, "")
        self.pClustering_tab = QtWidgets.QWidget()
        self.pClustering_tab.setObjectName("pClustering_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pClustering_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.c_byUserBox = QtWidgets.QGroupBox(self.pClustering_tab)
        self.c_byUserBox.setObjectName("c_byUserBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.c_byUserBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.c_byUserBox)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.c_byUserDescription = QtWidgets.QTextBrowser(self.widget_2)
        self.c_byUserDescription.setObjectName("c_byUserDescription")
        self.verticalLayout_8.addWidget(self.c_byUserDescription)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.c_byUser_clusterButton = QtWidgets.QPushButton(self.widget_3)
        self.c_byUser_clusterButton.setEnabled(False)
        self.c_byUser_clusterButton.setObjectName("c_byUser_clusterButton")
        self.horizontalLayout_10.addWidget(self.c_byUser_clusterButton)
        self.c_byUser_clusterProgressBar = QtWidgets.QProgressBar(self.widget_3)
        self.c_byUser_clusterProgressBar.setProperty("value", 0)
        self.c_byUser_clusterProgressBar.setObjectName("c_byUser_clusterProgressBar")
        self.horizontalLayout_10.addWidget(self.c_byUser_clusterProgressBar)
        self.verticalLayout_8.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.c_byUser_saveButton = QtWidgets.QPushButton(self.widget_4)
        self.c_byUser_saveButton.setEnabled(False)
        self.c_byUser_saveButton.setObjectName("c_byUser_saveButton")
        self.horizontalLayout_11.addWidget(self.c_byUser_saveButton)
        self.c_byUser_saveProgressBar = QtWidgets.QProgressBar(self.widget_4)
        self.c_byUser_saveProgressBar.setProperty("value", 0)
        self.c_byUser_saveProgressBar.setObjectName("c_byUser_saveProgressBar")
        self.horizontalLayout_11.addWidget(self.c_byUser_saveProgressBar)
        self.verticalLayout_8.addWidget(self.widget_4)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.verticalLayout_6.addWidget(self.c_byUserBox)
        self.groupBox_5 = QtWidgets.QGroupBox(self.pClustering_tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_5 = QtWidgets.QWidget(self.groupBox_5)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.c_byMovieDescription = QtWidgets.QTextBrowser(self.widget_5)
        self.c_byMovieDescription.setObjectName("c_byMovieDescription")
        self.verticalLayout_9.addWidget(self.c_byMovieDescription)
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.c_byMovie_clusterButton = QtWidgets.QPushButton(self.widget_6)
        self.c_byMovie_clusterButton.setEnabled(False)
        self.c_byMovie_clusterButton.setObjectName("c_byMovie_clusterButton")
        self.horizontalLayout_12.addWidget(self.c_byMovie_clusterButton)
        self.c_byMovie_clusterProgressBar = QtWidgets.QProgressBar(self.widget_6)
        self.c_byMovie_clusterProgressBar.setProperty("value", 0)
        self.c_byMovie_clusterProgressBar.setObjectName("c_byMovie_clusterProgressBar")
        self.horizontalLayout_12.addWidget(self.c_byMovie_clusterProgressBar)
        self.verticalLayout_9.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.c_byMovie_saveButton = QtWidgets.QPushButton(self.widget_7)
        self.c_byMovie_saveButton.setEnabled(False)
        self.c_byMovie_saveButton.setObjectName("c_byMovie_saveButton")
        self.horizontalLayout_13.addWidget(self.c_byMovie_saveButton)
        self.c_byMovie_saveProgressBar = QtWidgets.QProgressBar(self.widget_7)
        self.c_byMovie_saveProgressBar.setProperty("value", 0)
        self.c_byMovie_saveProgressBar.setObjectName("c_byMovie_saveProgressBar")
        self.horizontalLayout_13.addWidget(self.c_byMovie_saveProgressBar)
        self.verticalLayout_9.addWidget(self.widget_7)
        self.verticalLayout_10.addWidget(self.widget_5)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.pClustering_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setCheckable(False)
        self.actionQuit.setObjectName("actionQuit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionHelp)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Science Final Project"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Process Raw Netflix Data (This can take a long time)"))
        self.dataRatingsGroupBox.setTitle(_translate("MainWindow", "Load User Ratings Data (Provided by Netflix)"))
        self.decompressGroupBox.setTitle(_translate("MainWindow", "Decompress Ratings Data Files"))
        self.decompressButton.setText(_translate("MainWindow", "Decompress Ratings Data"))
        self.groupBox.setTitle(_translate("MainWindow", "Parse and Load Decompressed Data"))
        self.LoadButton.setText(_translate("MainWindow", "Load Data"))
        self.subsetRatingsDataBox.setTitle(_translate("MainWindow", "Instance Selection"))
        self.reduceMoviesGroup.setTitle(_translate("MainWindow", "Reduce Movies, removing those with too few ratings"))
        self.reduceMoviesButton.setText(_translate("MainWindow", "Reduce"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Reduce Users, removing those with too few ratings"))
        self.reduceUsersButton.setText(_translate("MainWindow", "Reduce"))
        self.SRSWRGroupBox.setTitle(_translate("MainWindow", "Further Reduce Users, using Simple Random Sampling with Replacement (SRSWR)"))
        self.reduceSRSWRButton.setText(_translate("MainWindow", "Reduce"))
        self.randomSeedGroupBox.setTitle(_translate("MainWindow", "Random Seed"))
        self.saveGroupBox.setTitle(_translate("MainWindow", "Save Reduced Netflix Ratings Data"))
        self.nd_saveButton.setText(_translate("MainWindow", "Save"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Load Pre-Processed and Reduced Netflix Data (Faster)"))
        self.nd_loadpreprocessed_Button.setText(_translate("MainWindow", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pNetflix_tab), _translate("MainWindow", "Netflix Data"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Load Previously Joined IMDB MetaData"))
        self.c_loadPIMDB_Button.setText(_translate("MainWindow", "Load Pre-Joined Data"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Load Netflix MetaData and Join with IMDB MetaData"))
        self.md_loadNetflix_Box.setTitle(_translate("MainWindow", "Load MetaData Provided by Netflix"))
        self.md_loadNetflix_button.setText(_translate("MainWindow", "Load"))
        self.md_joinBox.setTitle(_translate("MainWindow", "Join with IMDB Movie IDs (requires internet connection)"))
        self.md_joinIMDB_progressBar.setText(_translate("MainWindow", "Join"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Join with Addtional IMDB MetaData (requires internet connection)"))
        self.md_addIMDB_joinButton.setText(_translate("MainWindow", "Join"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Save Combined MetaData Content"))
        self.md_saveButton.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pMetaData_tab), _translate("MainWindow", "MetaData"))
        self.c_byUserBox.setTitle(_translate("MainWindow", "Cluster by Users"))
        self.c_byUserDescription.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TODO: This box can render HTML... include Description of Cluster operation (maybe html rendering of cost equation??.. maybe). Also describe save below, and probably warn about very long runtimes.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.c_byUser_clusterButton.setText(_translate("MainWindow", "Cluster"))
        self.c_byUser_saveButton.setText(_translate("MainWindow", "Save"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Cluster by Movies"))
        self.c_byMovieDescription.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TODO: This box can render HTML... include Description of Cluster operation (maybe html rendering of cost equation??.. maybe). Also describe save below, and probably warn about very long runtimes.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.c_byMovie_clusterButton.setText(_translate("MainWindow", "Cluster"))
        self.c_byMovie_saveButton.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pClustering_tab), _translate("MainWindow", "Clustering"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

