# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 784)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setObjectName("tabWidget")
        self.pNetflix_tab = QtWidgets.QWidget()
        self.pNetflix_tab.setAutoFillBackground(False)
        self.pNetflix_tab.setObjectName("pNetflix_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pNetflix_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.pNetflix_tab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.dataRatingsGroupBox = QtWidgets.QGroupBox(self.groupBox_8)
        self.dataRatingsGroupBox.setObjectName("dataRatingsGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dataRatingsGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.decompressGroupBox = QtWidgets.QGroupBox(self.dataRatingsGroupBox)
        self.decompressGroupBox.setObjectName("decompressGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.decompressGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.decompressButton = QtWidgets.QPushButton(self.decompressGroupBox)
        self.decompressButton.setObjectName("decompressButton")
        self.horizontalLayout.addWidget(self.decompressButton)
        self.decompressProgressBar = QtWidgets.QProgressBar(self.decompressGroupBox)
        self.decompressProgressBar.setProperty("value", 0)
        self.decompressProgressBar.setObjectName("decompressProgressBar")
        self.horizontalLayout.addWidget(self.decompressProgressBar)
        self.verticalLayout.addWidget(self.decompressGroupBox)
        self.groupBox = QtWidgets.QGroupBox(self.dataRatingsGroupBox)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LoadButton = QtWidgets.QPushButton(self.groupBox)
        self.LoadButton.setEnabled(False)
        self.LoadButton.setObjectName("LoadButton")
        self.horizontalLayout_2.addWidget(self.LoadButton)
        self.loadProgressBar = QtWidgets.QProgressBar(self.groupBox)
        self.loadProgressBar.setProperty("value", 0)
        self.loadProgressBar.setObjectName("loadProgressBar")
        self.horizontalLayout_2.addWidget(self.loadProgressBar)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_11.addWidget(self.dataRatingsGroupBox)
        self.subsetRatingsDataBox = QtWidgets.QGroupBox(self.groupBox_8)
        self.subsetRatingsDataBox.setObjectName("subsetRatingsDataBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.subsetRatingsDataBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.reduceMoviesGroup = QtWidgets.QGroupBox(self.subsetRatingsDataBox)
        self.reduceMoviesGroup.setObjectName("reduceMoviesGroup")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.reduceMoviesGroup)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.reduceMoviesButton = QtWidgets.QPushButton(self.reduceMoviesGroup)
        self.reduceMoviesButton.setEnabled(False)
        self.reduceMoviesButton.setObjectName("reduceMoviesButton")
        self.horizontalLayout_4.addWidget(self.reduceMoviesButton)
        self.groupBox_6 = QtWidgets.QGroupBox(self.reduceMoviesGroup)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.nd_movieRatingsCuttoffSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.nd_movieRatingsCuttoffSpinBox.setMaximum(1000)
        self.nd_movieRatingsCuttoffSpinBox.setProperty("value", 214)
        self.nd_movieRatingsCuttoffSpinBox.setObjectName("nd_movieRatingsCuttoffSpinBox")
        self.verticalLayout_9.addWidget(self.nd_movieRatingsCuttoffSpinBox)
        self.horizontalLayout_4.addWidget(self.groupBox_6)
        self.reduceMoviesProgressBar = QtWidgets.QProgressBar(self.reduceMoviesGroup)
        self.reduceMoviesProgressBar.setProperty("value", 0)
        self.reduceMoviesProgressBar.setObjectName("reduceMoviesProgressBar")
        self.horizontalLayout_4.addWidget(self.reduceMoviesProgressBar)
        self.verticalLayout_2.addWidget(self.reduceMoviesGroup)
        self.groupBox_2 = QtWidgets.QGroupBox(self.subsetRatingsDataBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.reduceUsersButton = QtWidgets.QPushButton(self.groupBox_2)
        self.reduceUsersButton.setEnabled(False)
        self.reduceUsersButton.setObjectName("reduceUsersButton")
        self.horizontalLayout_5.addWidget(self.reduceUsersButton)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.nd_userRatingsCutoffSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.nd_userRatingsCutoffSpinBox.setMaximum(200)
        self.nd_userRatingsCutoffSpinBox.setProperty("value", 30)
        self.nd_userRatingsCutoffSpinBox.setObjectName("nd_userRatingsCutoffSpinBox")
        self.verticalLayout_10.addWidget(self.nd_userRatingsCutoffSpinBox)
        self.horizontalLayout_5.addWidget(self.groupBox_5)
        self.reduceUsersProgressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.reduceUsersProgressBar.setProperty("value", 0)
        self.reduceUsersProgressBar.setObjectName("reduceUsersProgressBar")
        self.horizontalLayout_5.addWidget(self.reduceUsersProgressBar)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.SRSWRGroupBox = QtWidgets.QGroupBox(self.subsetRatingsDataBox)
        self.SRSWRGroupBox.setObjectName("SRSWRGroupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.SRSWRGroupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.reduceSRSWRButton = QtWidgets.QPushButton(self.SRSWRGroupBox)
        self.reduceSRSWRButton.setEnabled(False)
        self.reduceSRSWRButton.setObjectName("reduceSRSWRButton")
        self.horizontalLayout_6.addWidget(self.reduceSRSWRButton)
        self.randomSeedGroupBox = QtWidgets.QGroupBox(self.SRSWRGroupBox)
        self.randomSeedGroupBox.setObjectName("randomSeedGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.randomSeedGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.randomSeedSpinBox = QtWidgets.QSpinBox(self.randomSeedGroupBox)
        self.randomSeedSpinBox.setMaximum(10000)
        self.randomSeedSpinBox.setProperty("value", 42)
        self.randomSeedSpinBox.setObjectName("randomSeedSpinBox")
        self.verticalLayout_3.addWidget(self.randomSeedSpinBox)
        self.horizontalLayout_6.addWidget(self.randomSeedGroupBox)
        self.reduceSRSWRProgressBar = QtWidgets.QProgressBar(self.SRSWRGroupBox)
        self.reduceSRSWRProgressBar.setProperty("value", 0)
        self.reduceSRSWRProgressBar.setObjectName("reduceSRSWRProgressBar")
        self.horizontalLayout_6.addWidget(self.reduceSRSWRProgressBar)
        self.verticalLayout_2.addWidget(self.SRSWRGroupBox)
        self.verticalLayout_11.addWidget(self.subsetRatingsDataBox)
        self.saveGroupBox = QtWidgets.QGroupBox(self.groupBox_8)
        self.saveGroupBox.setObjectName("saveGroupBox")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.saveGroupBox)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.nd_saveButton = QtWidgets.QPushButton(self.saveGroupBox)
        self.nd_saveButton.setEnabled(False)
        self.nd_saveButton.setObjectName("nd_saveButton")
        self.horizontalLayout_16.addWidget(self.nd_saveButton)
        self.nd_saveProgressBar = QtWidgets.QProgressBar(self.saveGroupBox)
        self.nd_saveProgressBar.setProperty("value", 0)
        self.nd_saveProgressBar.setObjectName("nd_saveProgressBar")
        self.horizontalLayout_16.addWidget(self.nd_saveProgressBar)
        self.verticalLayout_11.addWidget(self.saveGroupBox)
        self.gridLayout_2.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pNetflix_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setCheckable(False)
        self.actionQuit.setObjectName("actionQuit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionHelp)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Science Final Project"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Process Raw Netflix Data (This can take a long time)"))
        self.dataRatingsGroupBox.setTitle(_translate("MainWindow", "Load User Ratings Data (Provided by Netflix)"))
        self.decompressGroupBox.setTitle(_translate("MainWindow", "Decompress Ratings Data Files"))
        self.decompressButton.setText(_translate("MainWindow", "Decompress Ratings Data"))
        self.groupBox.setTitle(_translate("MainWindow", "Parse and Load Decompressed Data"))
        self.LoadButton.setText(_translate("MainWindow", "Load Data"))
        self.subsetRatingsDataBox.setTitle(_translate("MainWindow", "Instance Selection"))
        self.reduceMoviesGroup.setTitle(_translate("MainWindow", "Reduce Movies, removing those with too few ratings"))
        self.reduceMoviesButton.setText(_translate("MainWindow", "Reduce"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Ratings Cutoff"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Reduce Users, removing those with too few ratings"))
        self.reduceUsersButton.setText(_translate("MainWindow", "Reduce"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Ratings Cutoff"))
        self.SRSWRGroupBox.setTitle(_translate("MainWindow", "Further Reduce Users, using Simple Random Sampling with Replacement (SRSWR)"))
        self.reduceSRSWRButton.setText(_translate("MainWindow", "Reduce"))
        self.randomSeedGroupBox.setTitle(_translate("MainWindow", "Random Seed"))
        self.saveGroupBox.setTitle(_translate("MainWindow", "Save Reduced Netflix Ratings Data"))
        self.nd_saveButton.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pNetflix_tab), _translate("MainWindow", "Netflix Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

